#!/bin/bash
if [ -d "/etc/squid/" ]; then
    payload="/etc/squid/payload.txt"
elif [ -d "/etc/squid3/" ]; then
	payload="/etc/squid3/payload.txt"
fi
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-10s\n' "ADD HOST TO SQUID PROXY" ; tput sgr0
if [ ! -f "$payload" ]
then
	tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "FILE $payload NOT FOUND" ; tput sgr0
	exit 1
else
	tput setaf 2 ; tput bold ; echo ""; echo "CURRENT DOMAINS IN FILE $payload:" ; tput sgr0
	tput setaf 3 ; tput bold ; echo "" ; cat $payload ; echo "" ; tput sgr0
	read -p "ENTER THE DOMAIN YOU WANT TO ADD TO THE LIST: " host
	if [[ -z $host ]]
	then
		tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "YOU HAVE ENTERED AN EMPTY OR NON-EXISTENT DOMAIN!" ; echo "" ; tput sgr0
		exit 1
	else
		if [[ `grep -c "^$host" $payload` -eq 1 ]]
		then
			tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "THE DOMAIN $host ALREADY EXISTS IN THE FILE $payload" ; echo "" ; tput sgr0
			exit 1
		else
			if [[ $host != \.* ]]
			then
				tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "YOU MUST ADD A DOMAIN BY STARTING IT WITH A DOT.!" ; echo "POR EXEMPLO: .YOUTUBE.COM" ; echo "IT IS NOT NECESSARY TO ADD SUBDOMAINS FOR DOMAINS THAT ARE ALREADY IN THE FILE." ; echo "IN OTHER WORDS, IT IS NOT NECESSARY TO ADD SMART.COM.KH" ; echo "IF THE DOMAIN .SMART.COM.KH IS ALREADY IN THE FILE." ; echo ""; tput sgr0
				exit 1
			else
				echo "$host" >> $payload && grep -v "^$" $payload > /tmp/a && mv /tmp/a $payload
				tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "File $payload updated, the domain was successfully added.:" ; tput sgr0
				tput setaf 3 ; tput bold ; echo "" ; cat $payload ; echo "" ; tput sgr0
				if [ ! -f "/etc/init.d/squid3" ]
				then
					service squid3 reload
				elif [ ! -f "/etc/init.d/squid" ]
				then
					service squid reload
				fi	
				tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Proxy Squid Proxy reloaded successfully!" ; echo "" ; tput sgr0
				exit 1
			fi
		fi
	fi
fi
