#!/bin/bash
IP=$(cat /etc/IP)
if [ ! -d /etc/VPSManager/userteste ]; then
mkdir /etc/VPSManager/userteste
fi
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "CREATE TEST USER" ; tput sgr0
echo ""
[ "$(ls -A /etc/VPSManager/userteste)" ] && echo -e "\033[1;32mACTIVE TEST!\033[1;37m" || echo -e "\033[1;31mNO ACTIVE TESTS!\033[0m"
echo ""
for testeson in $(ls /etc/VPSManager/userteste |sort |sed 's/.sh//g')
do
echo "$testeson"
done
echo ""
echo -ne "\033[1;32mUSER NAME\033[1;37m: "; read nome
if [[ -z $nome ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "EMPTY OR INVALID NAME." ; echo "" ; tput sgr0
	exit 1
fi
awk -F : ' { print $1 }' /etc/passwd > /tmp/users 
if grep -Fxq "$nome" /tmp/users
then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "THIS USER ALREADY EXISTS." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mPASSWORD\033[1;37m: "; read pass
if [[ -z $pass ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "EMPTY OR INVALID PASSWORD." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mLIMIT\033[1;37m: "; read limit
if [[ -z $limit ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "EMPTY OR INVALID LIMIT." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mMINUTES \033[1;33m(\033[1;31mEx: \033[1;37m60\033[1;33m)\033[1;37m: "; read u_temp
if [[ -z $limit ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "EMPTY OR INVALID LIMIT." ; echo "" ; tput sgr0
	exit 1
fi
useradd -M -s /bin/false $nome
(echo $pass;echo $pass) |passwd $nome > /dev/null 2>&1
echo "$pass" > /etc/VPSManager/senha/$nome
echo "$nome $limit" >> /root/usuarios.db
echo "#!/bin/bash
pkill -f "$nome"
userdel --force $nome
grep -v ^$nome[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/VPSManager/senha/$nome > /dev/null 2>&1
rm -rf /etc/VPSManager/userteste/$nome.sh
exit" > /etc/VPSManager/userteste/$nome.sh
chmod +x /etc/VPSManager/userteste/$nome.sh
at -f /etc/VPSManager/userteste/$nome.sh now + $u_temp min > /dev/null 2>&1
clear
echo -e "\E[44;1;37m     Usuario Teste Criado     \E[0m"
echo ""
echo -e "\033[1;32mIP:\033[1;37m $IP"
echo -e "\033[1;32mUSERNAME:\033[1;37m $nome"
echo -e "\033[1;32mPASSWORD:\033[1;37m $pass"
echo -e "\033[1;32mLIMIT:\033[1;37m $limit"
echo -e "\033[1;32mEXPIRY:\033[1;37m $u_temp Minutos"
echo ""
echo -e "\033[1;33mAFTER THE TIME DEFINED THE USER"
echo -e "\033[1;32m$nome \033[1;33mIT WILL BE DISCONNECTED AND DELETED.\033[0m"
exit
